<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageIcon>TCT_Icon-1.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="image\TCT_Icon-1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\My\ILogger\ILogger.csproj" />
    <ProjectReference Include="..\My\Judgment\Judgment.csproj" />
    <ProjectReference Include="..\My\OLogger\OLogger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="image\OSE-LOGO_CC-white-1.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="image\TCT_Icon-1.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="image\TCT_Icon-1.psd">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
